# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the app
COPY . .

# Build the project
RUN npm run build

EXPOSE 3000

CMD [ "node", "dist/index.js" ]
